FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Warsaw

# installing python, jdk8 and other tools
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y \ 
            git \
            curl \
            python3.8 \ 
            openjdk-8-jdk \ 
            build-essential  \ 
            unzip \ 
            zip

#installing gradle, kotlin from sdk, setting env path for gradle
RUN curl -s "https://get.sdkman.io" | bash && /bin/bash -c "source root/.sdkman/bin/sdkman-init.sh; sdk install kotlin; sdk install gradle"
ENV PATH=$PATH:/root/.sdkman/candidates/gradle/8.0.2/bin

# setting up the working directory
COPY . /root/proj
WORKDIR /root/proj
CMD gradle -q hello