FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive


# installing python, jdk8 and other tools
RUN apt-get update && apt install git curl -y
ENV TZ=Europe/Warsaw
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get -y update
RUN apt-get install -y -qq \ 
            python3.8 \ 
            openjdk-8-jdk \ 
            build-essential  \ 
            unzip \ 
            zip
# RUN apt-get update && \
#     apt-get install -y libsqlite3-dev

# deleting not necessary python version and deadsnakes repository
# not needed
RUN apt remove --purge python3.9
RUN add-apt-repository --remove ppa:deadsnakes/ppa

#installing gradle, kotlin from sdk, setting env path to gradle binaries
RUN curl -s "https://get.sdkman.io" | bash && /bin/bash -c "source root/.sdkman/bin/sdkman-init.sh; sdk install kotlin; sdk install gradle"
ENV PATH=$PATH:/root/.sdkman/candidates/gradle/8.0.2/bin

COPY . /root/proj
WORKDIR /root/proj
RUN echo kotlin --version

CMD gradle -q hello